// Code generated by irigencmd; DO NOT EDIT.
// 3d859b5d92a2c3d041545d014fa826f682ca06d056af8c7b31e32d930abf2bc5  https://web.archive.org/web/20200717224331if_/http://xmlns.com/foaf/spec/index.rdf

package foafiri

import "github.com/dpb587/rdfkit-go/rdf"

const Base rdf.IRI = "http://xmlns.com/foaf/0.1/"

const (
	// Indicates the name (identifier) associated with this online account.
	AccountName_Property = Base + "accountName"

	// Indicates a homepage of the service provide for this online account.
	AccountServiceHomepage_Property = Base + "accountServiceHomepage"

	// Indicates an account held by this agent.
	Account_Property = Base + "account"

	// The age in years of some agent.
	Age_Property = Base + "age"

	// An agent (eg. person, group, software or physical artifact).
	Agent_Class = Base + "Agent"

	// An AIM chat ID
	AimChatID_Property = Base + "aimChatID"

	// A location that something is based near, for some broadly human notion of near.
	Based_Near_Property = Base + "based_near"

	// The birthday of this Agent, represented in mm-dd string form, eg. '12-31'.
	Birthday_Property = Base + "birthday"

	// A current project this person works on.
	CurrentProject_Property = Base + "currentProject"

	// A depiction of some thing.
	Depiction_Property = Base + "depiction"

	// A thing depicted in this representation.
	Depicts_Property = Base + "depicts"

	// A checksum for the DNA of some thing. Joke.
	DnaChecksum_Property = Base + "dnaChecksum"

	// A document.
	Document_Class = Base + "Document"

	// The family name of some person.
	FamilyName_Property = Base + "familyName"

	// The family name of some person.
	Family_Name_Property = Base + "family_name"

	// The first name of a person.
	FirstName_Property = Base + "firstName"

	// The underlying or 'focal' entity associated with some SKOS-described concept.
	Focus_Property = Base + "focus"

	// An organization funding a project or person.
	FundedBy_Property = Base + "fundedBy"

	// A textual geekcode for this person, see http://www.geekcode.com/geek.html
	Geekcode_Property = Base + "geekcode"

	// The gender of this Agent (typically but not necessarily 'male' or 'female').
	Gender_Property = Base + "gender"

	// The given name of some person.
	GivenName_Property = Base + "givenName"

	// The given name of some person.
	Givenname_Property = Base + "givenname"

	// A class of Agents.
	Group_Class = Base + "Group"

	// Indicates an account held by this agent.
	HoldsAccount_Property = Base + "holdsAccount"

	// A homepage for some thing.
	Homepage_Property = Base + "homepage"

	// An ICQ chat ID
	IcqChatID_Property = Base + "icqChatID"

	// An image.
	Image_Class = Base + "Image"

	// An image that can be used to represent some thing (ie. those depictions which are particularly representative of
	// something, eg. one's photo on a homepage).
	Img_Property = Base + "img"

	// A page about a topic of interest to this person.
	Interest_Property = Base + "interest"

	// A document that this thing is the primary topic of.
	IsPrimaryTopicOf_Property = Base + "isPrimaryTopicOf"

	// A jabber ID for something.
	JabberID_Property = Base + "jabberID"

	// A person known by this person (indicating some level of reciprocated interaction between the parties).
	Knows_Property = Base + "knows"

	// A foaf:LabelProperty is any RDF property with texual values that serve as labels.
	LabelProperty_Class = Base + "LabelProperty"

	// The last name of a person.
	LastName_Property = Base + "lastName"

	// A logo representing some thing.
	Logo_Property = Base + "logo"

	// Something that was made by this agent.
	Made_Property = Base + "made"

	// An agent that made this thing.
	Maker_Property = Base + "maker"

	// A personal mailbox, ie. an Internet mailbox associated with exactly one owner, the first owner of this mailbox.
	// This is a 'static inverse functional property', in that there is (across time and change) at most one individual
	// that ever has any particular value for foaf:mbox.
	Mbox_Property = Base + "mbox"

	// The sha1sum of the URI of an Internet mailbox associated with exactly one owner, the first owner of the mailbox.
	Mbox_Sha1sum_Property = Base + "mbox_sha1sum"

	// Indicates a member of a Group
	Member_Property = Base + "member"

	// Indicates the class of individuals that are a member of a Group
	MembershipClass_Property = Base + "membershipClass"

	// An MSN chat ID
	MsnChatID_Property = Base + "msnChatID"

	// A Myers Briggs (MBTI) personality classification.
	MyersBriggs_Property = Base + "myersBriggs"

	// A name for some thing.
	Name_Property = Base + "name"

	// A short informal nickname characterising an agent (includes login identifiers, IRC and other chat nicknames).
	Nick_Property = Base + "nick"

	// An online account.
	OnlineAccount_Class = Base + "OnlineAccount"

	// An online chat account.
	OnlineChatAccount_Class = Base + "OnlineChatAccount"

	// An online e-commerce account.
	OnlineEcommerceAccount_Class = Base + "OnlineEcommerceAccount"

	// An online gaming account.
	OnlineGamingAccount_Class = Base + "OnlineGamingAccount"

	// An OpenID for an Agent.
	Openid_Property = Base + "openid"

	// An organization.
	Organization_Class = Base + "Organization"

	// A page or document about this thing.
	Page_Property = Base + "page"

	// A project this person has previously worked on.
	PastProject_Property = Base + "pastProject"

	// A person.
	Person_Class = Base + "Person"

	// A personal profile RDF document.
	PersonalProfileDocument_Class = Base + "PersonalProfileDocument"

	// A phone, specified using fully qualified tel: URI scheme (refs: http://www.w3.org/Addressing/schemes.html#tel).
	Phone_Property = Base + "phone"

	// A .plan comment, in the tradition of finger and '.plan' files.
	Plan_Property = Base + "plan"

	// The primary topic of some page or document.
	PrimaryTopic_Property = Base + "primaryTopic"

	// A project (a collective endeavour of some kind).
	Project_Class = Base + "Project"

	// A link to the publications of this person.
	Publications_Property = Base + "publications"

	// A homepage of a school attended by the person.
	SchoolHomepage_Property = Base + "schoolHomepage"

	// A sha1sum hash, in hex.
	Sha1_Property = Base + "sha1"

	// A Skype ID
	SkypeID_Property = Base + "skypeID"

	// A string expressing what the user is happy for the general public (normally) to know about their current activity.
	Status_Property = Base + "status"

	// The surname of some person.
	Surname_Property = Base + "surname"

	// A theme.
	Theme_Property = Base + "theme"

	// A derived thumbnail image.
	Thumbnail_Property = Base + "thumbnail"

	// A tipjar document for this agent, describing means for payment and reward.
	Tipjar_Property = Base + "tipjar"

	// Title (Mr, Mrs, Ms, Dr. etc)
	Title_Property = Base + "title"

	// A thing of interest to this person.
	Topic_Interest_Property = Base + "topic_interest"

	// A topic of some page or document.
	Topic_Property = Base + "topic"

	// A weblog of some thing (whether person, group, company etc.).
	Weblog_Property = Base + "weblog"

	// A work info homepage of some person; a page about their work for some organization.
	WorkInfoHomepage_Property = Base + "workInfoHomepage"

	// A workplace homepage of some person; the homepage of an organization they work for.
	WorkplaceHomepage_Property = Base + "workplaceHomepage"

	// A Yahoo chat ID
	YahooChatID_Property = Base + "yahooChatID"
)
