package exportgoiricmd

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/dpb587/rdfkit-go/cmd/rdfkit/cmdflags"
	"github.com/dpb587/rdfkit-go/cmd/rdfkit/cmdutil"
	"github.com/dpb587/rdfkit-go/encoding/trig/trigcontent"
	"github.com/dpb587/rdfkit-go/rdf"
	"github.com/spf13/cobra"
)

func New(app *cmdutil.App) *cobra.Command {
	var pkgName = ""
	var base string
	var prefix string
	var outPath string

	fIn := &cmdflags.EncodingInput{}

	cmd := &cobra.Command{
		Use:  "export-go-iri",
		Args: cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()

			if len(outPath) == 0 {
				return errors.New("output path required")
			}

			hasher := sha256.New()

			bfIn, err := fIn.Open(ctx, app.Registry, &cmdflags.EncodingInputOpenOptions{
				ReaderTee:           hasher,
				DecoderFallbackType: trigcontent.TypeIdentifier,
			})
			if err != nil {
				return fmt.Errorf("input: %v", err)
			}

			defer bfIn.Close()

			if len(pkgName) == 0 {
				workdir, err := os.Getwd()
				if err != nil {
					return fmt.Errorf("getwd: %v", err)
				}

				if len(outPath) > 0 {
					pkgName = filepath.Base(filepath.Dir(filepath.Join(workdir, outPath)))
				} else {
					pkgName = filepath.Base(workdir)
				}

				if pkgName == "." {
					pkgName = "iri"
				}
			}

			b := &builder{
				statementsBySubject: map[rdf.IRI]*builderSubject{},
			}

			decoderQuads := bfIn.GetQuadsDecoder()

			for decoderQuads.Next() {
				b.AddStatement(decoderQuads.Quad())
			}

			if err := decoderQuads.Err(); err != nil {
				return fmt.Errorf("decode[%s]: %v", bfIn.Decoder.GetContentTypeIdentifier(), err)
			}

			if len(base) == 0 {
				detectedBase, ok := b.DetectBase()
				if !ok {
					return errors.New("unable to detect base IRI")
				}

				base = detectedBase
			}

			b = b.FilterBase(rdf.IRI(base))

			if len(b.statementsBySubject) == 0 {
				return errors.New("no statements found")
			}

			outBuffer := bytes.NewBuffer(nil)

			fmt.Fprintf(outBuffer, `// Code generated by rdfkit; DO NOT EDIT.
// %x  %s

package %s

import "github.com/dpb587/rdfkit-go/rdf"

`,
				hasher.Sum(nil),
				bfIn.Reader.GetIRI(),
				pkgName,
			)

			_, err = b.WriteGoComment(outBuffer, rdf.IRI(b.baseTerm), "// ", true)
			if err != nil {
				return fmt.Errorf("write: %v", err)
			}

			_, err = fmt.Fprintf(outBuffer, "const %sBase rdf.IRI = %q\n", prefix, b.base)
			if err != nil {
				return fmt.Errorf("write: %v", err)
			}

			fmt.Fprintf(outBuffer, "\nconst (\n")

			var lastComment bool

			for termIdx, term := range b.ListDefinedTerms() {
				thisComment, err := b.WriteGoComment(outBuffer, term, "\t// ", termIdx == 0)
				if err != nil {
					return fmt.Errorf("write: %v", err)
				} else if lastComment && !thisComment {
					_, err = fmt.Fprintf(outBuffer, "\n")
					if err != nil {
						return fmt.Errorf("write: %v", err)
					}
				}

				lastComment = thisComment

				if strings.HasPrefix(string(term), string(b.base)) {
					_, err = fmt.Fprintf(outBuffer, "\t%[1]s%[2]s = %[1]sBase + %[3]q\n", prefix, b.GetGoIdent(term), strings.TrimPrefix(string(term), string(b.base)))
				} else {
					_, err = fmt.Fprintf(outBuffer, "\t%[1]s%[2]s = %q\n", prefix, b.GetGoIdent(term), term)
				}
				if err != nil {
					return fmt.Errorf("write: %v", err)
				}
			}

			_, err = fmt.Fprint(outBuffer, ")\n")
			if err != nil {
				return fmt.Errorf("write: %v", err)
			}

			formattedContents, err := format.Source(outBuffer.Bytes())
			if err != nil {
				return fmt.Errorf("gofmt: %v", err)
			}

			if outPath == "-" {
				_, err = os.Stdout.Write(formattedContents)
				if err != nil {
					return fmt.Errorf("write output: %v", err)
				}
			} else {
				fh, err := os.OpenFile(outPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
				if err != nil {
					return fmt.Errorf("open output: %v", err)
				}

				defer fh.Close()

				_, err = fh.Write(formattedContents)
				if err != nil {
					return fmt.Errorf("write output: %v", err)
				}
			}

			return nil
		},
	}

	f := cmd.Flags()
	fIn.Bind(f, "in", "i")
	f.StringVar(&base, "base", "", "vocab base IRI")
	f.StringVar(&prefix, "prefix", "", "optional prefix for tokens")
	f.StringVarP(&outPath, "out", "o", outPath, "go output file")

	return cmd
}
