// Code generated by irigencmd; DO NOT EDIT.
// d8c941c46d2e2b489a7e53b42601d999bf86aaa7295f1b65b31232ab65f46abf  http://www.w3.org/ns/rdfa.ttl

package rdfairi

import "github.com/dpb587/rdfkit-go/rdf"

const Base rdf.IRI = "http://www.w3.org/ns/rdfa#"

const (
	Context_Property          = Base + "context"
	Copy_Property             = Base + "copy"
	PGClass_Class             = Base + "PGClass"
	Pattern_Class             = Base + "Pattern"
	PrefixOrTermMapping_Class = Base + "PrefixOrTermMapping"
	Prefix_Property           = Base + "prefix"
	Term_Property             = Base + "term"
	Uri_Property              = Base + "uri"
	UsesVocabulary_Property   = Base + "usesVocabulary"
	Vocabulary_Property       = Base + "vocabulary"
)
