// Code generated by rdfkit; DO NOT EDIT.
// 6140e2c48125c790eb099e75bf079b726d43b92b87cb11e2f268ff8edfaa37aa  https://www.w3.org/ns/rdfa.ttl

package rdfairi

import "github.com/dpb587/rdfkit-go/rdf"

const Base rdf.IRI = "http://www.w3.org/ns/rdfa#"

const (
	Context_Property          = Base + "context"
	Copy_Property             = Base + "copy"
	PGClass_Class             = Base + "PGClass"
	Pattern_Class             = Base + "Pattern"
	PrefixOrTermMapping_Class = Base + "PrefixOrTermMapping"
	Prefix_Property           = Base + "prefix"
	Term_Property             = Base + "term"
	Uri_Property              = Base + "uri"
	UsesVocabulary_Property   = Base + "usesVocabulary"
	Vocabulary_Property       = Base + "vocabulary"
)
