// Code generated by irigencmd; DO NOT EDIT.
// 93d52b1a5824c7dd6504ca79c16205c0b740a0ba68b7a14952780f52561186a2  https://www.w3.org/1999/02/22-rdf-syntax-ns.ttl

package rdfiri

import "github.com/dpb587/rdfkit-go/rdf"

const Base rdf.IRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"

const (
	// The class of containers of alternatives.
	Alt_Class = Base + "Alt"

	// The class of unordered containers.
	Bag_Class = Base + "Bag"

	// A class representing a compound literal.
	CompoundLiteral_Class = Base + "CompoundLiteral"

	// The base direction component of a CompoundLiteral.
	Direction_Property = Base + "direction"

	// The first item in the subject RDF list.
	First_Property = Base + "first"

	// The datatype of RDF literals storing fragments of HTML content
	HTML_Datatype = Base + "HTML"

	// The datatype of RDF literals storing JSON content.
	JSON_Datatype = Base + "JSON"

	// The datatype of language-tagged string values
	LangString_Datatype = Base + "langString"

	// The language component of a CompoundLiteral.
	Language_Property = Base + "language"

	// The class of RDF Lists.
	List_Class = Base + "List"

	// The empty list, with no items in it. If the rest of a list is nil then the list has no more items in it.
	Nil_List = Base + "nil"

	// The object of the subject RDF statement.
	Object_Property = Base + "object"

	// The class of plain (i.e. untyped) literal values, as used in RIF and OWL 2
	PlainLiteral_Datatype = Base + "PlainLiteral"

	// The predicate of the subject RDF statement.
	Predicate_Property = Base + "predicate"

	// The class of RDF properties.
	Property_Class = Base + "Property"

	// The rest of the subject RDF list after the first item.
	Rest_Property = Base + "rest"

	// The class of ordered containers.
	Seq_Class = Base + "Seq"

	// The class of RDF statements.
	Statement_Class = Base + "Statement"

	// The subject of the subject RDF statement.
	Subject_Property = Base + "subject"

	// The subject is an instance of a class.
	Type_Property = Base + "type"

	// Idiomatic property used for structured values.
	Value_Property = Base + "value"

	// The datatype of XML literal values.
	XMLLiteral_Datatype = Base + "XMLLiteral"
)
