// Code generated by irigencmd; DO NOT EDIT.
// ecee3a011b7c13ea2a7e40b0a208bfe6be53d69fdd53ee035e09e9f9e5108ad6  https://www.w3.org/2000/01/rdf-schema.ttl

package rdfsiri

import "github.com/dpb587/rdfkit-go/rdf"

const Base rdf.IRI = "http://www.w3.org/2000/01/rdf-schema#"

const (
	// The class of classes.
	Class_Class = Base + "Class"

	// A description of the subject resource.
	Comment_Property = Base + "comment"

	// The class of container membership properties, rdf:_1, rdf:_2, ..., all of which are sub-properties of 'member'.
	ContainerMembershipProperty_Class = Base + "ContainerMembershipProperty"

	// The class of RDF containers.
	Container_Class = Base + "Container"

	// The class of RDF datatypes.
	Datatype_Class = Base + "Datatype"

	// A domain of the subject property.
	Domain_Property = Base + "domain"

	// The definition of the subject resource.
	IsDefinedBy_Property = Base + "isDefinedBy"

	// A human-readable name for the subject.
	Label_Property = Base + "label"

	// The class of literal values, eg. textual strings and integers.
	Literal_Class = Base + "Literal"

	// A member of the subject resource.
	Member_Property = Base + "member"

	// A range of the subject property.
	Range_Property = Base + "range"

	// The class resource, everything.
	Resource_Class = Base + "Resource"

	// Further information about the subject resource.
	SeeAlso_Property = Base + "seeAlso"

	// The subject is a subclass of a class.
	SubClassOf_Property = Base + "subClassOf"

	// The subject is a subproperty of a property.
	SubPropertyOf_Property = Base + "subPropertyOf"
)
