// Code generated by irigencmd; DO NOT EDIT.
// 4cde74807d5e31e58cc462ea6c1b1fc8fc0cf5bdbf8ac224ef95525efbeb2879  https://www.w3.org/ns/earl

package earliri

import "github.com/dpb587/rdfkit-go/rdf"

const Base rdf.IRI = "http://www.w3.org/ns/earl#"

const (
	// assertor of an assertion
	AssertedBy_ObjectProperty = Base + "assertedBy"

	// a statement that embodies the results of a test
	Assertion_Class = Base + "Assertion"

	// an entity such as a person, a software tool, an organization, or any other grouping that carries out a test
	// collectively
	Assertor_Class = Base + "Assertor"

	Automatic_TestMode = Base + "automatic"

	// Formal schema of the Evaluation and Report Language (EARL) 1.0
	BaseOwlOntology = "http://www.w3.org/ns/earl"

	// the class of outcomes to denote an undetermined outcome
	CannotTell_Class = Base + "CannotTell"

	CantTell_CannotTell = Base + "cantTell"

	// the class of outcomes to denote failing a test
	Fail_Class = Base + "Fail"

	Failed_Fail                = Base + "failed"
	Inapplicable_NotApplicable = Base + "inapplicable"

	// additional warnings or error messages in a human-readable form
	Info_DatatypeProperty = Base + "info"

	// assertor that is primarily responsible for performing the test
	MainAssertor_ObjectProperty = Base + "mainAssertor"

	Manual_TestMode = Base + "manual"

	// mode in which the test was performed
	Mode_ObjectProperty = Base + "mode"

	// the class of outcomes to denote the test is not applicable
	NotApplicable_Class = Base + "NotApplicable"

	// the class of outcomes to denote the test has not been carried out
	NotTested_Class = Base + "NotTested"

	// a discrete value that describes a resulting condition from carrying out the test
	OutcomeValue_Class = Base + "OutcomeValue"

	// outcome of performing the test
	Outcome_ObjectProperty = Base + "outcome"

	// the class of outcomes to denote passing a test
	Pass_Class = Base + "Pass"

	Passed_Pass = Base + "passed"

	// location within a test subject that are most relevant to a test result
	Pointer_ObjectProperty = Base + "pointer"

	// result of an assertion
	Result_ObjectProperty = Base + "result"

	SemiAuto_TestMode = Base + "semiAuto"

	// any piece of software such as an authoring tool, browser, or evaluation tool
	Software_Class = Base + "Software"

	// test subject of an assertion
	Subject_ObjectProperty = Base + "subject"

	// an atomic test, usually one that is a partial test for a requirement
	TestCase_Class = Base + "TestCase"

	// a testable statement, usually one that can be passed or failed
	TestCriterion_Class = Base + "TestCriterion"

	// describes how a test was carried out
	TestMode_Class = Base + "TestMode"

	// a higher-level requirement that is tested by executing one or more sub-tests
	TestRequirement_Class = Base + "TestRequirement"

	// the actual result of performing the test
	TestResult_Class = Base + "TestResult"

	// the class of things that have been tested against some test criterion
	TestSubject_Class = Base + "TestSubject"

	// test criterion of an assertion
	Test_ObjectProperty = Base + "test"

	Undisclosed_TestMode = Base + "undisclosed"
	UnknownMode_TestMode = Base + "unknownMode"
	Untested_NotTested   = Base + "untested"
)
